spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fileserver
    username: root
    password: Mukhtar1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect